apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cqy0qjbey-nodejs
  janus-idp.io/tekton: cqy0qjbey-nodejs
  backstage.io/kubernetes-id: cqy0qjbey-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cqy0qjbey-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
