apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cqy0qjbey-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cqy0qjbey-nodejs 
  name: cqy0qjbey-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cqy0qjbey-nodejs 
