apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cqy0qjbey-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-17abe1674d.iy3c.p3.openshiftapps.com/rhtap/rhtap-qe:2d417ac45c1b811d54291121f276cf6d58e445f1@sha256:e085048bff72888a6ab6868a6bd3080a548dcf82daee6dabaa5879d775fc4ce9
          name: container-image
